import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/components/ui/GlobalLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const Loader = () => (
//   <div
//     style={{
//       display: "flex",
//       height: "100vh",
//       width: "100%",
//       alignItems: "center",
//       justifyContent: "center",
//     }}
//   >
//     <div
//       style={{
//         width: 40,
//         height: 40,
//         borderRadius: "50%",
//         border: "4px solid #6366f1",
//         borderTopColor: "transparent",
//         animation: "spin 0.7s linear infinite",
//       }}
//     />
//     <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
//   </div>
// );

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-black! flex flex-col">
        <GlobalProvider>
            {children}
        </GlobalProvider>
      </body>
    </html>
  );
}