"""Alembic script template"""
"""Add telemetry columns

Revision ID: 371977a11f9a
Revises: 7c43f8c0a000
Create Date: 2026-06-24 16:48:28.018705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '371977a11f9a'
down_revision = '7c43f8c0a000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_ingestion_runs', sa.Column('extractor_version', sa.String(length=50), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('schema_version', sa.String(length=50), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('llm_input_tokens', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('llm_output_tokens', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('extraction_duration_ms', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('graph_write_duration_ms', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('total_duration_ms', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('nodes_created', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('relationships_created', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('nodes_merged', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('relationships_merged', sa.Integer(), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('document_category', sa.String(length=100), nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('sample_entities', sa.JSON(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('sample_triplets', sa.JSON(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('baseline_entities_per_chunk', sa.Float(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('current_entities_per_chunk', sa.Float(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('deviation_percent', sa.Float(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('baseline_documents', sa.Integer(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('fallback_chunks', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_document_ingestion_runs_document_category'), 'document_ingestion_runs', ['document_category'], unique=False)
    op.add_column('document_table_rows', sa.Column('part_number', sa.String(length=255), nullable=True))
    op.add_column('document_table_rows', sa.Column('product_name', sa.String(length=1000), nullable=True))
    op.add_column('document_table_rows', sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('document_table_rows', sa.Column('gst', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('document_table_rows', sa.Column('hsn_code', sa.String(length=100), nullable=True))
    op.add_column('document_table_rows', sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True))
    op.create_index(op.f('ix_document_table_rows_mrp'), 'document_table_rows', ['mrp'], unique=False)
    op.create_index(op.f('ix_document_table_rows_part_number'), 'document_table_rows', ['part_number'], unique=False)
    op.create_index(op.f('ix_document_table_rows_product_name'), 'document_table_rows', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('excel_sheets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workbook_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('col_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('excel_sheets_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workbook_id'], ['excel_workbooks.id'], name=op.f('excel_sheets_workbook_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('excel_sheets_pkey'))
    )
    op.create_index(op.f('ix_excel_sheets_workbook_id'), 'excel_sheets', ['workbook_id'], unique=False)
    op.create_index(op.f('ix_excel_sheets_tenant_id'), 'excel_sheets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_excel_sheets_id'), 'excel_sheets', ['id'], unique=False)
    op.create_table('excel_cells',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('column_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['excel_column_profiles.id'], name=op.f('excel_cells_column_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['excel_rows.id'], name=op.f('excel_cells_row_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('excel_cells_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('excel_cells_pkey'))
    )
    op.create_index(op.f('ix_excel_cells_tenant_id'), 'excel_cells', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_excel_cells_row_id'), 'excel_cells', ['row_id'], unique=False)
    op.create_index(op.f('ix_excel_cells_id'), 'excel_cells', ['id'], unique=False)
    op.create_index(op.f('ix_excel_cells_column_id'), 'excel_cells', ['column_id'], unique=False)
    op.create_table('excel_rows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sheet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['excel_sheets.id'], name=op.f('excel_rows_sheet_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('excel_rows_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('excel_rows_pkey'))
    )
    op.create_index(op.f('ix_excel_rows_tenant_id'), 'excel_rows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_excel_rows_sheet_id'), 'excel_rows', ['sheet_id'], unique=False)
    op.create_index(op.f('ix_excel_rows_id'), 'excel_rows', ['id'], unique=False)
    op.create_table('excel_workbooks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kb_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('excel_workbooks_kb_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('excel_workbooks_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('excel_workbooks_pkey')),
    sa.UniqueConstraint('kb_id', name=op.f('excel_workbooks_kb_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_excel_workbooks_tenant_id'), 'excel_workbooks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_excel_workbooks_kb_id'), 'excel_workbooks', ['kb_id'], unique=False)
    op.create_index(op.f('ix_excel_workbooks_id'), 'excel_workbooks', ['id'], unique=False)
    op.create_table('spreadsheet_cells',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kb_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sheet_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cell_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('spreadsheet_cells_kb_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('spreadsheet_cells_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('spreadsheet_cells_pkey'))
    )
    op.create_index(op.f('ix_spreadsheet_cells_id'), 'spreadsheet_cells', ['id'], unique=False)
    op.create_index(op.f('ix_cells_tenant_id'), 'spreadsheet_cells', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cells_sheet_row'), 'spreadsheet_cells', ['sheet_name', 'row_id'], unique=False)
    op.create_index(op.f('ix_cells_kb_id'), 'spreadsheet_cells', ['kb_id'], unique=False)
    op.create_index(op.f('ix_cells_column_val'), 'spreadsheet_cells', ['column_name', 'cell_value'], unique=False)
    op.create_table('excel_column_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sheet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('col_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('is_entity', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['excel_sheets.id'], name=op.f('excel_column_profiles_sheet_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('excel_column_profiles_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('excel_column_profiles_pkey'))
    )
    op.create_index(op.f('ix_excel_column_profiles_id'), 'excel_column_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_excel_cols_tenant_id'), 'excel_column_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_excel_cols_sheet_id'), 'excel_column_profiles', ['sheet_id'], unique=False)
    # ### end Alembic commands ###
