"""Alembic script template"""
"""Add integrated agent fields

Revision ID: 490295dad675
Revises: a1b2c3d4e5f6
Create Date: 2026-06-01 19:21:21.254197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490295dad675'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_type', sa.String(length=50), nullable=False))
    op.add_column('agents', sa.Column('organization_name', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('agents', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('website_url', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('fallback_message_enabled', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('brand_persona', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'brand_persona')
    op.drop_column('agents', 'fallback_message_enabled')
    op.drop_column('agents', 'website_url')
    op.drop_column('agents', 'contact_email')
    op.drop_column('agents', 'contact_phone')
    op.drop_column('agents', 'organization_name')
    op.drop_column('agents', 'agent_type')
    # ### end Alembic commands ###
