"""Alembic script template"""
"""Re-add schema

Revision ID: 4d1890d88283
Revises: 490295dad675
Create Date: 2026-06-12 12:00:20.152221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d1890d88283'
down_revision = '490295dad675'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cells_column_val'), table_name='spreadsheet_cells')
    op.drop_index(op.f('ix_cells_kb_id'), table_name='spreadsheet_cells')
    op.drop_index(op.f('ix_cells_sheet_row'), table_name='spreadsheet_cells')
    op.drop_index(op.f('ix_cells_tenant_id'), table_name='spreadsheet_cells')
    op.drop_index(op.f('ix_spreadsheet_cells_id'), table_name='spreadsheet_cells')
    op.drop_table('spreadsheet_cells')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spreadsheet_cells',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kb_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sheet_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cell_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('spreadsheet_cells_kb_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('spreadsheet_cells_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('spreadsheet_cells_pkey'))
    )
    op.create_index(op.f('ix_spreadsheet_cells_id'), 'spreadsheet_cells', ['id'], unique=False)
    op.create_index(op.f('ix_cells_tenant_id'), 'spreadsheet_cells', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cells_sheet_row'), 'spreadsheet_cells', ['sheet_name', 'row_id'], unique=False)
    op.create_index(op.f('ix_cells_kb_id'), 'spreadsheet_cells', ['kb_id'], unique=False)
    op.create_index(op.f('ix_cells_column_val'), 'spreadsheet_cells', ['column_name', 'cell_value'], unique=False)
    # ### end Alembic commands ###
