"""Alembic script template"""
"""Add Gmail models

Revision ID: 7c43f8c0a000
Revises: 4d1890d88283
Create Date: 2026-06-16 17:38:51.394286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c43f8c0a000'
down_revision = '4d1890d88283'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_messages_message_id'), 'gmail_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_gmail_messages_sender'), 'gmail_messages', ['sender'], unique=False)
    op.create_index(op.f('ix_gmail_messages_sync_status'), 'gmail_messages', ['sync_status'], unique=False)
    op.create_index(op.f('ix_gmail_messages_thread_id'), 'gmail_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_gmail_messages_user_id'), 'gmail_messages', ['user_id'], unique=False)
    op.create_index('ix_gmail_user_msg', 'gmail_messages', ['user_id', 'message_id'], unique=False)
    op.create_table('gmail_sync_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=True),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_sync_state_user_id'), 'gmail_sync_state', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_sync_state_user_id'), table_name='gmail_sync_state')
    op.drop_table('gmail_sync_state')
    op.drop_index('ix_gmail_user_msg', table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_user_id'), table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_thread_id'), table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_sync_status'), table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_sender'), table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_message_id'), table_name='gmail_messages')
    op.drop_table('gmail_messages')
    # ### end Alembic commands ###
