name: Secure GRAG Deployment

on:
  push:
    branches:
      - backdev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          command_timeout: 10m
          script: |
            cd /home/GRAG/backend
            chmod +x deploy.sh
            ./deploy.sh
